### ISSUE TITLE
Events are all fired on page load

### ISSUE THREAD

**Issue by hj84** [pupunzi/jquery.mb.YTPlayer#157] opened 2015-12-07 11:36 UTC
I worked with a previous version of the plugin, but that one is now full of errors (chrome extensions, youtube errors) probably caused by the YouTube API. In the latest version, it looks like all events are launched after the page has loaded, while they're indicating that they only should do something whenever the function is triggered.

$('#bgndVideo').on("YTPEnd",function(){
// For example this function is triggered and fired after loading the page
});

The result is a glitching page that loads all these events one time. (YTPStart, YTPPause, YTPEnd)
These functions / events used to work before.

See http://www.filedropper.com/videotest for an example of what I mean. You'll find comments in the videotest.js file.

**Comment by pupunzi** [comment] 2015-12-07 15:51
Hi,
The errors you get for the Chrome extension "is now removed from Chrome canary and should be fixed for all users around mid-January 2016".
This is a known bug with the official Chromecast JavaScript library. Instead of failing silently, it dumps these error messages in all non-Chrome browsers as well as Chrome browsers where the Chromecast extension isn't present.

I'm not able to reproduce the behavior you are describing ("it looks like all events are launched after the page has loaded"); in the 2.9.4, the only event fired once the player is ready and start playing was the YTPPause ... just before the YTPStart. This issue has been fixed in the 2.9.7 available for download. All the other events are fired correctly once the YT API trigger them.

Try with the latest and let me know.

Bye,
Matteo

**Comment by hj84** [comment] 2015-12-08 06:32
Hi,
Thank you for the update and for your reply.

I think the YTPPause function is still fired before the end of the video. This is the case without using the YTPPause function:

Preview screen with play button
Hit play, preview screen disappears
Video becomes visible and starts playing
Video can't be paused by user (bad)
After the video, the outro screen becomes visible and the preview screen is still hidden (good)

This is what happens when using the YTPPause function:

Preview screen with play button
Hit play, preview screen disappears
Video becomes visible and starts playing
Video can be paused by user (good)
After the video, the preview screen becomes visible again for a moment (glitch) and after that, the outro screen is visible (bad)

In the file that you can download I've included the latest version of the plugin. Also, in the videotest.js file you can uncomment the code in the YTPPause function to see the difference between the two scenario's.

I've been using display none/block, opacity and visibility styles as well as jQuery show, hide and animate. It doesn't matter in the scenario described above, since I think it has something to do with the YTPPause function that is triggered (again) before the video ends.

I hope there's something you can do with the behaviour of the YTPPause function.

Files: http://www.filedropper.com/videotest_1

**Closed** 2016-01-06 18:33 UTC

**Comment by hj84** [comment] 2016-01-07 09:44
Hi Matteo,
Is this issue resolved/fixed?
Thanks, HJ
