### ISSUE TITLE
Latest Version Freezes on Safari

### ISSUE THREAD

**Issue by SkaeKost** [pupunzi/jquery.mb.YTPlayer#177] opened 2016-05-02 17:19 UTC
Everything appears like it is going to work... loading screen fades away, initial video panel comes into view, but then stops.

If I adjust my window size just a tad it starts playing. If I change my setting "stopMovieOnBlur:false", back to True, then click off the Browser, then click back on the movie starts to play, but it will not start playing on it's own.
Autoplay is set to True...

I also tested by removing all other javascript on my site and did a completely fresh install of the mb.YTPlayer js code, images, fonts and css, but nothing fixes this problem.

Safari Version 9.1
Mac Version 10.10.5

**Comment by air720boarder** [comment] 2016-05-04 20:53
Bumping for this. I need to horizontally resize the window for it to work

**Comment by macsamiro** [comment] 2016-05-06 14:46
plus 1

**Comment by ramono** [comment] 2016-05-09 09:57
Plus 2

I've been unsuccessfully looking around to see if I can find a solution.

**Comment by pupunzi** [comment] 2016-05-09 11:05
With the latest 3.0.1(https://github.com/pupunzi/jquery.mb.YTPlayer/releases) that issue should be fixed with a"terrible" workaround :-)
Give it a try and let me know.

**Comment by ramono** [comment] 2016-05-13 08:20
Hi,

Thanks for the quick response (and for such useful work). I'm still having the issue of Safari autoplay, but I manage to make a workaround ("terrible" as well) that seems to work, by reading the state of the player and make it play when ready or when the user scrolls to it.

This change also solved another issue I was having on Safari where the video would not loop, and it just kept loading after the first play. This is working fine now.

Thanks.

**Comment by SkaeKost** [comment] 2016-05-16 19:02
Yeah, unfortunately the update didn't fix my issue either. Was there another workaround, I know desktop Safari isn't as important as Chrome, Firefox or IE versions, but it would be nice to get this puppy working on that platform as well.

**Comment by pupunzi** [comment] 2016-05-16 19:29
I'm testing with Safari Versione 9.1 (11601.5.17.1) and OSX version 10.11.4 (15E65)
I'm not able to reproduce the freeze issue anymore.

Can you provide the exact configuration you have?

**Comment by SkaeKost** [comment] 2016-05-16 19:37
<a id=“bgndVideo" class="player" data-property="{videoURL:’http://www.youtube.com/watch?v=BSfCnSqx0LM',containment:'#home',autoPlay:true,mute:true,startAt:0,opacity:1,showControls:false,stopMovieOnBlur:false}”>youtube</a>

Here is the site: http://vapsfl.com <http://vapsfl.com/>

Like I mentioned before, it works on all browsers and it does work on Safari, but only on a window resize.

Thank you for your fast response!!


Steven Kropp

Sevell + Sevell, Inc.
939 North High Street, Suite 205
Columbus, Ohio 43201

email.<kropp@sevell.com <mailto:kropp@sevell.com>>
w <http://web.www.sevell.com/>eb <http://web.www.sevell.com/>. <http://web.www.sevell.com/>www.sevell.com <http://web.www.sevell.com/>
phone.614.341.9700

**Comment by pupunzi** [comment] 2016-05-16 20:55
@SkaeKost
Just tested your site with Safari Versione 9.1 (11601.5.17.1) and OSX version 10.11.4 (15E65)
and the video starts immediately... what OSX version and what Safari version are you testing with?

**Comment by SkaeKost** [comment] 2016-05-17 13:11
Safari Version 9.1.1 (10601.6.17) and OSX 10.10.5

I will say every once in a while the video would play, and I thought I had solved it—then I would refresh the browser to test a couple of times to test and then it would go back to freezing again.


Steven Kropp

Sevell + Sevell, Inc.
939 North High Street, Suite 205
Columbus, Ohio 43201

email.<kropp@sevell.com <mailto:kropp@sevell.com>>
w <http://web.www.sevell.com/>eb <http://web.www.sevell.com/>. <http://web.www.sevell.com/>www.sevell.com <http://web.www.sevell.com/>
phone.614.341.9700

**Comment by pupunzi** [comment] 2016-05-17 17:02
@SkaeKost For me it's working fine each time I load the page... the most relevant difference is the OSX version... don't know...

**Comment by SkaeKost** [comment] 2016-05-20 17:57
Very strange… well, maybe it is just an issue with my machine only, thank you so much for all of your help.


Steven Kropp

Sevell + Sevell, Inc.
939 North High Street, Suite 205
Columbus, Ohio 43201

email.<kropp@sevell.com <mailto:kropp@sevell.com>>
w <http://web.www.sevell.com/>eb <http://web.www.sevell.com/>. <http://web.www.sevell.com/>www.sevell.com <http://web.www.sevell.com/>
phone.614.341.9700

**Comment by alanontheweb** [comment] 2016-05-24 21:05
Having this issue as well unfortunately. Video starts playing in Safari after a resize event.

**Comment by pupunzi** [comment] 2016-05-24 22:46
@alanontheweb you should provide the URL of the page where the issue is happening.

**Comment by alanontheweb** [comment] 2016-05-24 22:48
I will, but it's a local project at the moment. I fixed it by adding - 

  $(".background-container").on("YTPReady",function(e){
  	setTimeout(function() {
		$(".background-container").YTPPlay();
			}, 0);
});

**Comment by pupunzi** [comment] 2016-06-25 12:41
With the new 3.0.6 release this issue should be really closed :-)

**Closed by pupunzi** 2016-06-25 12:41 UTC
