### ISSUE TITLE
Is optimizeDisplay() suppose to emulate object-fit?

### ISSUE THREAD

**Issue by Zauberfisch** [pupunzi/jquery.mb.YTPlayer#350] opened 2018-04-13 08:14 UTC
In previous versions of this plugin, a video would be sized and positioned to emulate object-fit (similar to background-size: cover, meaning the video fills the whole element).

However, this is no longer the case. Was this feature removed on purpose or is this a bug?

Left (Blue) part of the image below is the desired result. Right (Red) side is the current behaviour.
![icamigivutfeokidnawgunudmoagcebs](https://user-images.githubusercontent.com/186158/38723704-70908820-3ef1-11e8-91ab-ee7276d79d7c.png)

my current work around is:

    .inline-YTPlayer {
        height: 100% !important;
        width: 100% !important;
        max-width: none !important;
        max-height: none !important;
    }
    .inline-YTPlayer .mb_YTPlayer {
        height: 100% !important;
        padding-bottom: 0 !important;
    }

The code to center and scale the video is technically still there, what seems to be the problem is a wrapper div (`div.inline-YTPlayer`) that is wrapped around the containment div (`div.mb_YTPlayer`) which does not use `height:100%`. 
Additionally, the containment div (`div.mb_YTPlayer`) also seems to always be scaled by aspect ratio but the iframe has an absolute size, so the aspect ratio of that div doesn't actually matter.

If this is a bug, I think a overhaul/cleanup of the whole `optimizeDisplay()` method is desirable, to clearly separate "object-fit" mode vs "scale by aspect ratio" mode.

PS: this issue is talking about behaviour with the config `{optimizeDisplay:true}`. If optimizeDisplay is set to false, the plugin behaves as expected as far as I can tell.

**Comment by pupunzi** [comment] 2018-04-13 17:26
Hi,
the YTPlayer perform this behavior if initialized as player (containment is "self" or the same element where it is declared). This is not a bug; you should create a separate element where the player properties are defined and a container where the player will be rendered. that way it will be initialized as background of the containment element and not as crome-less player.

If you have an URL where I can see the player in action I can suggest you the correct way to initialize it.

All the best,
M

**Closed** 2018-04-17 15:54 UTC

**Comment by pzstar** [comment] 2018-08-01 17:32
Same problem here. Previously i could easily show the video as a background filling the whole container under the containment:'self'. It would add the .mbYTP_wrapper container under the section that is declared. But now div .inline-YTPlayer is wrapped over the declared section. Previously there would not be this div. It would just add .mbYTP_wrapper container under the declared section.

Also, the additional CSS padding-bottom: 56.25%; is added on a declared div which it stretching the video beyond the container.

**Comment by pzstar** [comment] 2018-08-01 17:53
VM49600:1 Uncaught ReferenceError: auto is not defined
    at eval (eval at jQuery.fn.optimizeDisplay (VM49424 jquery.mb.YTPlayer.min.js:9), <anonymous>:1:1)
    at a.fn.init.jQuery.fn.optimizeDisplay (VM49424 jquery.mb.YTPlayer.min.js:9)
    at VM49424 jquery.mb.YTPlayer.min.js:8
    at dispatch (VM49368 jquery.js:3)
    at r.handle (VM49368 jquery.js:3)
    at Object.trigger (VM49368 jquery.js:3)
    at Object.a.event.trigger (VM49369 jquery-migrate.min.js:2)
    at VM49368 jquery.js:3
    at Function.each (VM49368 jquery.js:2)
    at a.fn.init.each (VM49368 jquery.js:2)

Also it would be very kind of you if you can tell me what does this error mean?

**Comment by Zauberfisch** [comment] 2018-08-01 22:05
yeah, it's definitely a bug, I didn't react because It felt like @pupunzi didn't really read my bug report, and unfortunately I didn't have the time back then to argue.

So I just went ahead and "forked" an earlier version into my projects directly and modified it there.

@pzstar if you want to debug it yourself or post a useful stack trace here, make sure that you include the  `jquery.mb.YTPlayer.js` instead of the `jquery.mb.YTPlayer.min.js` (no min) so that it's actually possible to see what line the error is in.
Plus you should also include what version of the plugin you are using (see the line "Build:  7xxx" in the top of the .js file)

**Comment by pupunzi** [comment] 2018-08-07 16:54
As already explained it is not a bug. If you initialize the player with a "self" containment it is intended as a chromeless player and not as background video. In the case of containment = "self" the "inline-YTPlayer" class is added and the player is formatted to maintain the video aspect-ratio. If you don't want this behavior then the video declaration must be different from the containment element. Check the demo files to see the different behaviors.

**Comment by joseangeljimenez** [comment] 2018-08-18 10:42
Thanks @Zauberfisch, your CSS modifications work like a charm!
P.S.: I couldn't get the desired behaviour (object fit) by simply changing the containment param.

**Comment by molhambakir** [comment] 2020-03-25 13:31
I have tried the same method by changing (optimizeDisplay:!0) to (optimizeDisplay:!1) 
It worked but got other options of YT missed up! not sure If it's a bug! 
My youtube profile and logo and share button shouldn't show on hover! ![image](https://user-images.githubusercontent.com/2674933/77541642-5e1caa80-6ebe-11ea-93bf-2618f4e05942.png)
